### ISSUE TITLE
Java arguments should be in camelCase

### ISSUE THREAD

**Issue by PiekJ** [yarwest/Yet-Another-Coding-Guideline#1]
As suggested in the title: the arguments of methods and constructors should be in camelCase. Some examples:
`public Exam(String name, String course) { ... }`
`public void setName(String name) { ... }`

When having the name of the argument identifier is the same as property of a class. The `this` keyword should be used. Example:
`public void setName(String name) {
    this.name = name;
}`

**Comment by yarwest** [comment]
Point 1 is already covered.
> All variables and function names should be written in camel casing if the language allows this.

The second point has been added to the [Object Orientated Programming section](https://github.com/yarwest/Yet-Another-Coding-Guideline#oop).
